### ISSUE TITLE
t1 bomber micro ability

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#218]
check the physics values of the blueprint, it seems like it is easier to micro the bomber than the other factional counterparts

**Comment by Ithilis** [comment]
It will be because it dont use bomb as other bombers, but missiles similar as corsair. The physic is total same as other bombers have. 

That also mean its probably easier to micro and harder to dodge. It is realy a problem ? or have lowest aoe (2,6) and 300dmg and should work as mini corsair.   Maybe we should decrese aoe to 2,5 what mean it will be weaker against building (pgens) while will hit less pgens. But this microability is kind of problem of oficial balance (that i was multiple time mention...)

**Comment by CookieNoob** [comment]
well no its not a real problem at all, I just saw it in a replay that it was much easier to micro. If the physics are identical, we can just ignore it.
