### ISSUE TITLE
t3 pgen starts at 0% when rebuild on wreck

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#258]

**Comment by CookieNoob** [comment]
happened to Farmsletje in 5991021

**Comment by JJ173** [comment]
Could just be that his wreckage took some damage. If the wreckage take damage, it takes longer to rebuild the structure. Perhaps the unit that blew it left a bit of damage on the wreckage, causing it to take longer to rebuild. I however, cannot reproduce this issue either.

**Comment by CookieNoob** [comment]
no, the wreck had at least 2k mass in it.

**Comment by Exotic-Retard** [comment]
also the funny joke is that there is no rebuild penalty if the wreck is damaged via overkill damage since that reduces its mass cost but doesnt decrease its hp as it should, or something. we know this since you could rebuild t2 mexes at 50% from a 0hp wreck when they had 3000hp and were tmled

so this is some other issue i guess.
