### ISSUE TITLE
wreck of t2 transport spawns unfolded when unit is killed

### ISSUE THREAD

**Issue by CookieNoob** [Nomads-Project/nomads#293]
relevant function:
https://github.com/Nomads-Project/nomads/blob/f184d0a295b8193d29d1e47614effe843e34ff20/units/INA2001/INA2001_Script.lua#L56

this should set the folding rate to 0, maybe the wreck should be set to the correct animation fraction

**Comment by CookieNoob** [comment]
no idea how to fix this :/

**Comment by JJ173** [comment]
Looking in to it.

**Comment by Exotic-Retard** [comment]
this is kinda strange since it seems that TryCopyPose fails - its what makes wrecks like the titan stay in that shape after a death animation

perhaps adding a death animation could solve this, but thing is that it would be from one of two possible positions, so an actual animation would either not work or have to be special code there. an empty anim might work

**Comment by JJ173** [comment]
Fixed. 

Adding this to the transport BP fixed the issue:

```     
    AnimationDeath = {
            {
                Animation = '/units/INA2001/INA2001_Unfold.sca',
                AnimationRateMax = 1.25,
                AnimationRateMin = 0.75,
                Weight = 100,
            },
        },
```

Images to show:
![image](https://user-images.githubusercontent.com/17053495/27050655-4351c31e-4fab-11e7-9171-39e75fe94196.png)

I also added `self:DestroyThrusterEffects()`  to the script of the transport to destroy the units thruster effect when it's killed.
