### ISSUE TITLE
fix nomads t2 emp tank projectiles

### ISSUE THREAD

**Issue by Exotic-Retard** [Nomads-Project/nomads#34]
getting some onimpact error there, just need to go through it and make sure its working again.

**Comment by CookieNoob** [comment]
note: Issue is most probably that self:DisableUnitIntel() is called without any argument

since here https://github.com/FAForever/fa/blob/6bfdf7f04f5fd3a09d02884d68dc4d68a1a54666/lua/sim/Unit.lua#L2355
the table requires exactly these arguments...

compare to the usage of this function in FAF:
https://github.com/FAForever/fa/search?p=1&q=DisableUnitIntel&type=Code&utf8=%E2%9C%93
