### ISSUE TITLE
refactor nomads t3 arty

### ISSUE THREAD

**Issue by Exotic-Retard** [Nomads-Project/nomads#75]
its quite buggy.

when the arty dies the satellite remains, and in some cases it can still fire when it dead, spamming log with errors.

also if you kill + rebuild arty you can have a bunch of satellites there.
whats more is that the satellites are invisible to the enemy team, even with full intel on.

**Comment by CookieNoob** [comment]
I checked the code for the arty and it seems like the sat searches for a new base station when the old one dies. During that time it is unable to fire, but if it eventually finds a new station it will fly there and the new station doesnt generate a new sat. At least thats how its supposed to work

**Comment by CookieNoob** [comment]
as it turns out most of the errors in the log only happen when you spawn the arty with cheats, when you build the sats it works quite well...

groundfire still needs to be fixed and also that the arty seems to shoot a bit too far

**Comment by CookieNoob** [comment]
groundfire with the sat is still a matter of luck, I added some debug lines to the files that are involved and it seems like the sat gets the target coordinates transfered correctly and is trying to shoot it but after a short time it loses the target again (the function OnLostTarget in defeultweapons.lua is called)

**Comment by TheKeyBlue** [comment]
Wait is this fixed completely? Cause i only mentioned it in my commit since it was about the same unit.

**Comment by CookieNoob** [comment]
the thing that isnt working is the targeting, there is a separate issue for that #48. I looked through the code and the sats are reassigned to a new station when the old station dies, thats intended (it works well when the arty is build one by one instead of spawning multiple artys at the same time). I couldnt verify that the sat was able to shoot while the main building is not existent. Killing the arty and rebuilding it wont create new satellites.

This warning still remains: 
WARNING: INO2302: Buffs sections in parent and slave unit blueprints do not match
but I will create a different issue for that.
